DROP DATABASE IF EXISTS `yiishop`;

CREATE DATABASE `yiishop` CHARACTER SET utf8 COLLATE utf8_bin;

USE yiishop;

CREATE TABLE authority 
(
    Id          INT UNSIGNED    NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name        VARCHAR(50)        NOT NULL,
    Description VARCHAR(200)       DEFAULT NULL,
    Rank        TINYINT(1)      DEFAULT 1,
	Status		TINYINT(1) 		DEFAULT 1
);

INSERT INTO authority (Name,Description)
VALUES('Admin','Administrator');

CREATE TABLE user
(
    Id          INT UNSIGNED    NOT NULL AUTO_INCREMENT PRIMARY KEY,
    AuthId      INT UNSIGNED    NOT NULL,
    UserName    VARCHAR(50)        NOT NULL,
	Phone		VARCHAR(20)		DEFAULT NULL,
    Password    VARCHAR(200)    NOT NULL,
	FullName	VARCHAR(100)	NOT NULL,
	Address 	VARCHAR(200)	DEFAULT NULL,
	CitizenId	CHAR(100)		NOT NULL,
	Email		VARCHAR(100)	DEFAULT NULL,
	SocialNet	VARCHAR(100)	DEFAULT NULL,
	Images		VARCHAR(150)	DEFAULT NULL,
	Notes		VARCHAR(100)	DEFAULT NULL,
	Rank		TINYINT(1)		DEFAULT NULL,
    Status      TINYINT(1)      DEFAULT 1,
    Date        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (AuthId) REFERENCES authority (Id)
);

INSERT INTO user (AuthId,UserName,Password,FullName,CitizenId)
VALUES (1,'admin','123456','Quan tri vien','00000000');

CREATE TABLE category 
(
    Id          INT UNSIGNED    NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name        VARCHAR(50)        NOT NULL,
	Price		INT UNSIGNED	NOT NULL,
    Description VARCHAR(150)       DEFAULT NULL,
    Date        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Status      TINYINT(1)
);

CREATE TABLE category_history
(
	Id 			INT UNSIGNED 	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CategoryId	INT UNSIGNED 	NOT NULL,
	Price 		INT UNSIGNED 	NOT NULL,
	Date 		TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UserId		INT UNSIGNED 	NOT NULL,
	Notes		VARCHAR(50)		DEFAULT NULL,
	FOREIGN KEY (CategoryId) REFERENCES category (Id),
	FOREIGN KEY (UserId)	REFERENCES user (Id)
);

CREATE TABLE product_group
(
	Id 			INT UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Name		VARCHAR(80)		NOT NULL,
	Note		VARCHAR(250)		NOT NULL,
	Rank 		TINYINT			DEFAULT 1,
	Status		TINYINT			DEFAULT 1
);

CREATE TABLE product
(
    Id          INT UNSIGNED    NOT NULL AUTO_INCREMENT PRIMARY KEY ,
    Name        VARCHAR(150)    NOT NULL,
    CategoryId  INT UNSIGNED    NOT NULL,
    Price       INT UNSIGNED    DEFAULT NULL,
    Discount    INT UNSIGNED    DEFAULT NULL,
    PriceExtra  INT UNSIGNED    DEFAULT NULL,
    Images      VARCHAR(100)    DEFAULT NULL,
	GroupId		INT UNSIGNED	NOT NULL,
    Date        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DateUpdate  TIMESTAMP       NULL DEFAULT NULL,
    Rank        TINYINT      	DEFAULT 0,
    UserId      INT UNSIGNED    NOT NULL,
	Description	TEXT			DEFAULT NULL,
	Tags		VARCHAR(150)	DEFAULT NULL,
	Interaction INT UNSIGNED	DEFAULT NULL,
    Status      TINYINT(1)      DEFAULT 1,
    FOREIGN KEY (CategoryId) REFERENCES category (Id) ON DELETE CASCADE,
	FOREIGN KEY (GroupId) REFERENCES product_group (Id) ON DELETE CASCADE,
    INDEX (UserId,CategoryId)
);

CREATE TABLE pictures
(
	Id 			INT UNSIGNED 	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ProductId	INT UNSIGNED	DEFAULT 0,
	Image 		VARCHAR(100)		NOT NULL,
	Date		TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (ProductId) REFERENCES product (Id)
);

CREATE TABLE cart
(
	Id 			INT UNSIGNED 	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	UserId		INT UNSIGNED 	NOT NULL,
	Date 		TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Price 		INT UNSIGNED	NOT NULL,
	Discount	INT UNSIGNED	DEFAULT NULL,
	Price_plus	INT	UNSIGNED	DEFAULT NULL,
	Status		TINYINT(1)		DEFAULT 1,
	Notes		VARCHAR(200)	DEFAULT NULL,
	FOREIGN KEY (UserId) REFERENCES user (Id) ON DELETE CASCADE,
	INDEX (UserId)
);

/* *******************************************************************	
	Chưa tạo Cart_details để tạo list các sản phẩm trong cart
	Chưa tạo Notifications để thông báo các thông tin cho khách hàng
	Chưa tạo Bill và Bill_details để khách hàng đặt hàng
 */

CREATE TABLE saving # Khách hàng gửi vàng
(
	Id 			INT UNSIGNED 	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Code		VARCHAR(50)		NOT NULL UNIQUE,
	UserId		INT UNSIGNED 	NOT NULL,
	NotaryId	INT UNSIGNED 	NOT NULL,
	Phone		VARCHAR(15)		NOT NULL,
	Images 		CHAR(100)		DEFAULT NULL,
	Contract 	TEXT			NOT NULL,
	Description VARCHAR(200)	DEFAULT NULL,
	Date 		TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	DateUpdate 	TIMESTAMP 		NULL DEFAULT NULL,
	Quantity 	FLOAT 			NOT NULL,
	Earning		FLOAT 			NOT NULL,
	Notes		TEXT			DEFAULT NULL,
	Interaction	INT UNSIGNED	DEFAULT 0,
	Status		TINYINT(1)		DEFAULT 1,
	FOREIGN KEY (UserId) REFERENCES user (Id),
	FOREIGN KEY (NotaryId) REFERENCES user (Id),
	INDEX (Code)
);

CREATE TABLE saving_interactions
(
	Id 			INT UNSIGNED 	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	SavingId	INT UNSIGNED 	NOT NULL,
	UserId		INT UNSIGNED	NOT NULL,
	Comment 	VARCHAR(100)	DEFAULT NULL,
	Date 		TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Status 		TINYINT(1) 		DEFAULT 1,
	FOREIGN KEY (UserId) REFERENCES user (Id),
	FOREIGN KEY (SavingId) REFERENCES saving (Id)
);

CREATE TABLE ledger 
(
    Id          INT UNSIGNED    NOT NULL AUTO_INCREMENT PRIMARY KEY,
	ProductId	INT UNSIGNED 	DEFAULT NULL,
	CartId		INT	UNSIGNED 	DEFAULT NULL,
    UserId      INT UNSIGNED    NOT NULL,
	Date        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Actions		VARCHAR(50)		DEFAULT NULL,
    Content     TEXT            NOT NULL,
    Content2    VARCHAR(150)    DEFAULT NULL,
    Status      TINYINT(1)      DEFAULT 1,
    FOREIGN KEY (UserId) REFERENCES user (Id) ON DELETE CASCADE,
    INDEX (UserId)
);

CREATE TABLE posts
(
	Id			INT UNSIGNED	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Title		VARCHAR(100) 	NOT NULL,
	Content		TEXT			NOT NULL,
	UserId		INT UNSIGNED 	NOT NULL,
	Date		TIMESTAMP		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	Status		TINYINT(1) 		DEFAULT 1,
	FOREIGN KEY (UserId) REFERENCES user (Id) ON DELETE CASCADE
);

CREATE TABLE posts_images
(
	Id 			INT UNSIGNED 	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PostsId		INT UNSIGNED	DEFAULT 0,
	Image 		VARCHAR(100)	NOT NULL,
	Date		TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (PostsId	) REFERENCES posts (Id)
);

CREATE TABLE banner
(
	Id		INT UNSIGNED 		NOT NULL AUTO_INCREMENT PRIMARY KEY,
	Title	VARCHAR(100)		NOT NULL,
	Content	TEXT				NOT NULL,
	Images	VARCHAR(100)		DEFAULT NULL,
	UserId	INT UNSIGNED		NOT NULL,
	Status 	TINYINT(1) 			DEFAULT 1,
	Date	TIMESTAMP 			NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (UserId) REFERENCES user (Id) ON DELETE CASCADE
);

CREATE TABLE banner_images
(
	Id 			INT UNSIGNED 	NOT NULL AUTO_INCREMENT PRIMARY KEY,
	BannerId	INT UNSIGNED	DEFAULT 0,
	Image 		VARCHAR(100)	NOT NULL,
	Date		TIMESTAMP 		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (BannerId) REFERENCES banner (Id)
);